import fs from 'fs';
import zlib from 'zlib';
import path from 'path';

const sourceDir = path.join(process.cwd(), 'src', 'data');
const outputArg = process.argv[2]; // Get the output dir or file from the command line

if (!outputArg) {
  console.error('Please provide an output directory or file.');
  process.exit(1);
}

const outputPath = path.resolve(process.cwd(), outputArg);

const files = fs.readdirSync(sourceDir).filter(file => file.endsWith('.json'));

if (path.extname(outputPath) === '.ts') {
    // Generate a single TS file with base64 exports
    let tsContent = `// This file is generated by scripts/compress-json.ts
`;
    
    files.forEach(file => {
        const sourcePath = path.join(sourceDir, file);
        const fileContents = fs.readFileSync(sourcePath);
        const compressed = zlib.gzipSync(fileContents);
        const base64 = compressed.toString('base64');
        const variableName = path.basename(file, '.json');
        tsContent += `export const ${variableName} = '${base64}';\n`;
    });

    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, tsContent);
    console.log(`Generated compressed data to ${outputPath}`);

} else {
    // Original functionality: create gzipped files in a directory
    const destDir = outputPath;

    // Ensure the destination directory exists
    if (!fs.existsSync(destDir)) {
      fs.mkdirSync(destDir, { recursive: true });
    }

    files.forEach(file => {
      const sourcePath = path.join(sourceDir, file);
      const destPath = path.join(destDir, `${file}.gz`);

      const fileContents = fs.readFileSync(sourcePath);
      const compressed = zlib.gzipSync(fileContents);

      fs.writeFileSync(destPath, compressed);

      console.log(`Compressed ${file} to ${destPath}`);
    });
}
