import fs from 'fs';
import path from 'path';
import { encode } from '@toon-format/toon';

const sourceDir = path.join(process.cwd(), 'src', 'data');
const outputArg = process.argv[2];

if (!outputArg) {
    console.error('Please provide an output directory or file.');
    process.exit(1);
}

const outputPath = path.resolve(process.cwd(), outputArg);
const files = fs.readdirSync(sourceDir).filter(file => file.endsWith('.json'));

if (path.extname(outputPath) === '.ts') {
    let tsContent = `// This file is generated by scripts/convert-to-toon.ts\n`;
    files.forEach(file => {
        const sourcePath = path.join(sourceDir, file);
        const jsonContent = fs.readFileSync(sourcePath, 'utf-8');
        const jsonData = JSON.parse(jsonContent);
        const toonData = encode(jsonData);
        const variableName = path.basename(file, '.json');
        tsContent += `export const ${variableName} = \`${toonData.replace(/\\/g, '\\\\').replace(/`/g, '\\`')}\`;\n`;
    });

    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, tsContent);
    console.log(`Generated TOON data to ${outputPath}`);
} else {
    const outputDir = outputPath;
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    files.forEach(file => {
        const sourcePath = path.join(sourceDir, file);
        const destPath = path.join(outputDir, file.replace('.json', '.toon'));

        const jsonContent = fs.readFileSync(sourcePath, 'utf-8');
        const jsonData = JSON.parse(jsonContent);
        const toonData = encode(jsonData);

        fs.writeFileSync(destPath, toonData);
        console.log(`Converted ${file} to ${destPath}`);
    });
}
