import fs from 'fs';
import path from 'path';
import { encode } from '@toon-format/toon';
import pako from 'pako';

const sourceDir = path.join(process.cwd(), 'src', 'data');
const outputArg = process.argv[2];

if (!outputArg) {
    console.error('Please provide an output directory or file.');
    process.exit(1);
}

const outputPath = path.resolve(process.cwd(), outputArg);
const files = fs.readdirSync(sourceDir).filter(file => file.endsWith('.json'));

if (path.extname(outputPath) === '.ts') {
    let tsContent = `// This file is generated by scripts/convert-to-toon.ts\n`;
    tsContent += `// Data is compressed with gzip for smaller bundle size\n`;

    files.forEach(file => {
        const sourcePath = path.join(sourceDir, file);
        const jsonContent = fs.readFileSync(sourcePath, 'utf-8');
        const jsonData = JSON.parse(jsonContent);
        const toonData = encode(jsonData);

        // Compress the TOON data
        const compressed = pako.deflate(toonData);
        const base64Compressed = Buffer.from(compressed).toString('base64');

        const variableName = path.basename(file, '.json');
        const originalSize = (toonData.length / 1024).toFixed(2);
        const compressedSize = (base64Compressed.length / 1024).toFixed(2);
        const reduction = ((1 - base64Compressed.length / toonData.length) * 100).toFixed(1);

        tsContent += `// ${variableName}: ${originalSize}KB -> ${compressedSize}KB (${reduction}% reduction)\n`;
        tsContent += `export const ${variableName} = "${base64Compressed}";\n`;

        console.log(`  ${file}: ${originalSize}KB -> ${compressedSize}KB (${reduction}% smaller)`);
    });

    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, tsContent);
    console.log(`Generated compressed TOON data to ${outputPath}`);
} else {
    const outputDir = outputPath;
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    files.forEach(file => {
        const sourcePath = path.join(sourceDir, file);
        const destPath = path.join(outputDir, file.replace('.json', '.toon'));

        const jsonContent = fs.readFileSync(sourcePath, 'utf-8');
        const jsonData = JSON.parse(jsonContent);
        const toonData = encode(jsonData);

        fs.writeFileSync(destPath, toonData);
        console.log(`Converted ${file} to ${destPath}`);
    });
}
