/**
 * Compress CSV source files into a TypeScript bundle.
 *
 * Reads from src/data-csv/*.csv (generated by migrate-psgc.ts directly from XLSX)
 * and outputs gzip-deflate + base64 encoded strings into a single .ts file.
 *
 * Usage:
 *   bun scripts/convert-to-csv.ts src/data-csv-ts/index.ts
 */

import fs from 'fs';
import path from 'path';
import pako from 'pako';

const sourceDir = path.join(process.cwd(), 'src', 'data-csv');
const outputArg = process.argv[2];

if (!outputArg) {
    console.error('Please provide an output file path (e.g. src/data-csv-ts/index.ts)');
    process.exit(1);
}

const outputPath = path.resolve(process.cwd(), outputArg);

if (!fs.existsSync(sourceDir)) {
    console.error(`Source directory not found: ${sourceDir}`);
    console.error('Run: bun run migrate:psgc --file=<filename.xlsx>  to generate CSV files first.');
    process.exit(1);
}

const files = fs.readdirSync(sourceDir).filter(f => f.endsWith('.csv')).sort();

if (files.length === 0) {
    console.error('No .csv files found in', sourceDir);
    process.exit(1);
}

let tsContent = `// This file is auto-generated by scripts/convert-to-csv.ts\n`;
tsContent += `// Source: src/data-csv/*.csv (generated from PSGC XLSX via migrate-psgc.ts)\n`;
tsContent += `// Encoding: gzip deflate → base64\n`;
tsContent += `// Do not edit manually.\n\n`;

for (const file of files) {
    const sourcePath = path.join(sourceDir, file);
    const csvText = fs.readFileSync(sourcePath, 'utf-8');

    const compressed = pako.deflate(csvText);
    const base64Compressed = Buffer.from(compressed).toString('base64');

    const variableName = path.basename(file, '.csv');
    const originalKb = (Buffer.byteLength(csvText, 'utf-8') / 1024).toFixed(2);
    const compressedKb = (base64Compressed.length / 1024).toFixed(2);
    const reduction = ((1 - base64Compressed.length / Buffer.byteLength(csvText, 'utf-8')) * 100).toFixed(1);

    tsContent += `// ${variableName}: ${originalKb}KB → ${compressedKb}KB (${reduction}% reduction)\n`;
    tsContent += `export const ${variableName} = "${base64Compressed}";\n`;

    console.log(`  ${file}: ${originalKb}KB → ${compressedKb}KB (${reduction}% smaller)`);
}

const outputDir = path.dirname(outputPath);
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, tsContent);
console.log(`Generated compressed CSV bundle at ${outputPath}`);
